version: '3'

networks:
  frontend:
  backend:

services:
  mysql:
    container_name: vue-blog-mysql
    image: mariadb:10.2
    restart: unless-stopped
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: bhunter
      MYSQL_DATABASE: vue-blog
      MYSQL_USER: root
      MYSQL_PASSWORD: bhunter
  server:
    container_name: vue-blog-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    environment:
      BLOG_DB_HOST: mysql
      BLOG_DB_USER: root
      BLOG_DB_PASSWORD: bhunter
    volumes:
      - ../api:/var/www/vue-blog/api:rw
      - ../public:/var/www/vue-blog/public:rw
    ports:
      - "8080:80"
